general {
    disable_loading_bar = true
    hide_cursor = false
}

background {
    monitor =
    path = /home/rahatut/Pictures/Wallpapers/wallpaper.png

    blur_passes = 3
    blur_size = 5

    noise = 0.01
    contrast = 1.0
    brightness = 0.68
    vibrancy = 0.12
}
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"

    color = rgb(cdd6f4)
    font_size = 52
    font_family = JetBrainsMono Nerd Font

    position = 0, 175
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"

    color = rgba(205,214,244,0.55)
    font_size = 13
    font_family = JetBrainsMono Nerd Font

    position = 0, 122
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER

    color = rgb(a6e3a1)
    font_size = 16
    font_family = JetBrainsMono Nerd Font

    position = 0, 62
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 300, 48
    outline_thickness = 2

    dots_size = 0.18
    dots_spacing = 0.28
    dots_center = true

    outer_color = rgb(a6e3a1)
    inner_color = rgba(30,30,46,0.45)
    font_color = rgb(cdd6f4)

    fade_on_empty = false
    placeholder_text = Password...

    rounding = 24

    check_color = rgb(a6e3a1)
    fail_color = rgb(f38ba8)

    position = 0, -12
    halign = center
    valign = center
}

